DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
  id   INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  PROV VARCHAR(20),
  CITY NVARCHAR(20)
);

INSERT INTO ADDRESS(PROV, CITY) VALUES ('hunan','changsha');
