DROP  TABLE IF EXISTS TEACHER;
CREATE TABLE  TEACHER (id INT NOT NULL  PRIMARY KEY AUTO_INCREMENT ,NAME VARCHAR (20));
INSERT INTO TEACHER(NAME) VALUES ('liu');
INSERT INTO TEACHER(NAME) VALUES ('gao');
INSERT INTO TEACHER(NAME) VALUES ('chen');
INSERT INTO TEACHER(NAME) VALUES ('zhou');
INSERT INTO TEACHER(NAME) VALUES ('xiong');
