DROP TABLE IF EXISTS TEACHER;
CREATE TABLE TEACHER (
  id   INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20)
);
INSERT INTO TEACHER (NAME) VALUES ('liu');
INSERT INTO TEACHER (NAME) VALUES ('gao');
INSERT INTO TEACHER (NAME) VALUES ('chen');
INSERT INTO TEACHER (NAME) VALUES ('zhou');
INSERT INTO TEACHER (NAME) VALUES ('xiong');


CREATE TABLE STUDENT (
  id      INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  NAME    VARCHAR(20),
  age     INT,
  ADDRESS VARCHAR(20)
)
  DEFAULT CHARSET = utf8;
INSERT INTO STUDENT (NAME, age, ADDRESS) VALUES ('s1', 25, 'hunan');
INSERT INTO STUDENT (NAME, age, ADDRESS) VALUES ('s2', 26, 'changsha');
INSERT INTO STUDENT (NAME, age, ADDRESS) VALUES ('s3', 27, 'changde');
INSERT INTO STUDENT (NAME, age, ADDRESS) VALUES ('s4', 28, 'hanshou');
INSERT INTO STUDENT (NAME, age, ADDRESS) VALUES ('s5', 30, 'yiyang');

CREATE TABLE ADDRESS (
  id   INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  prov VARCHAR(20),
  CITY NVARCHAR(20)
);


CREATE TABLE COURSE (
  id   INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20)
);

INSERT  INTO COURSE(NAME) VALUES ('语文');
INSERT  INTO COURSE(NAME) VALUES ('数学');
INSERT  INTO COURSE(NAME) VALUES ('英语');
